const Erros = {
  CPF_INVALIDO: 'CPF_INVALIDO',
  DESCONHECIDO: 'DESCONHECIDO',
  ID_INVALIDO: 'ID_INVALIDO',
  NOME_CARACTERES_INVALIDOS: 'NOME_CARACTERES_INVALIDOS',
  NOME_GRANDE: 'NOME_GRANDE',
  NOME_PEQUENO: 'NOME_PEQUENO',
  NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
  NOME_VAZIO: 'NOME_VAZIO',
  SENHA_INVALIDA: 'SENHA_INVALIDA',
  SENHA_FRACA: 'SENHA_FRACA',
  EMAIL_INVALIDO: 'EMAIL_INVALIDO',
  SENHA_HASH_INVALIDA: 'SENHA_HASH_INVALIDA',
} as const;

export default Erros;
